name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    strategy:
      matrix:
        pg-version: [9.6, 10, 11, 12, 13]
        postgis-version: [3.1, 2.5]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            PG_VERSION=${{ matrix.pg-version }}
            POSTGIS_VERSION=${{ matrix.postgis-version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.pg-version }}-${{ matrix.postgis-version }}
